### ISSUE TITLE
error after plugin reload (not critical)

### ISSUE THREAD

**Issue by LKirillK** [72-S/CommandBridge#6]
after pb reload on proxy server
i get this error on paper server

[22:26:58 INFO]: [CommandBridge] Command registered successfully from script: example-bukkit.yml
[22:26:58 ERROR]: Caught previously unhandled exception :
[22:26:58 ERROR]: Paper Async Command Builder Thread Pool - 2
java.util.ConcurrentModificationException: null
        at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:1023) ~[?:?]
        at java.base/java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:1052) ~[?:?]
        at net.minecraft.commands.Commands.fillUsableCommands(Commands.java:537) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.commands.Commands.sendAsync(Commands.java:496) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.commands.Commands.lambda$sendCommands$6(Commands.java:475) ~[paper-1.21.jar:1.21-124-df3b654]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by 72-S** [comment]
fixed in 2.0.0
